name: Build Python Package

on: [push, pull_request]

jobs:
    check-package:
      name: Smoke test our package on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
          python-version: ["3.8", "3.9", "3.10", "3.11"]
          sims: ["SADDsims_FullArray_001", "SADDsims_MonitoringArray_001" ]

      steps:
        - name: Check out source repository
          uses: actions/checkout@v4

        - name: Set up Python environment
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - if: $${{ matrix.sims }}
          run: cd sims/${{ matrix.sims }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Generate data
          # This depends on some specific naming of files
          # TODO Do this better!
          run: python gendata.py

        - name: Run simulation
          # This depends on some specific naming of files
          # TODO Do this better!
          run: python compute_metrics_*.py
